{
    'name': 'ESG CSRD',
    'version': '1.0',
    'category': 'Hidden',
    'summary': 'CSRD integration with ESG',
    'depends': ['esg', 'survey', 'accountant_knowledge'],
    'data': [
        'security/esg_security.xml',
        'security/ir.model.access.csv',
        'data/esg.esrs.csv',
        'data/esg.nace.csv',
        'data/esg_metric_survey_data.xml',
        'data/mail_template_data.xml',
        'data/esg_csrd_knowledge_article_template_category_data.xml',
        'data/esg_csrd_knowledge_article_template_csrd_data.xml',
        'data/esg_csrd_knowledge_article_template_vsme_data.xml',
        'views/esg_esrs_views.xml',
        'views/esg_metric_views.xml',
        'views/esg_report_views.xml',
        'views/knowledge_article_views.xml',
        'views/survey_user_input_views.xml',
        'views/res_config_settings_views.xml',
        'views/esg_menus.xml',
        'wizard/esg_metric_ask_feedback_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'esg_csrd/static/src/**/*',
        ],
    },
    'auto_install': ['esg'],
    'author': 'Odoo S.A.',
    'license': 'OEEL-1',
}
